# Generated by Django 5.1.4 on 2026-06-22 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coletas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número do laudo')),
                ('versao', models.PositiveSmallIntegerField(default=1, verbose_name='Versão')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('criticidade_geral', models.CharField(blank=True, max_length=8, verbose_name='Criticidade geral')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico técnico')),
                ('recomendacoes', models.TextField(blank=True, verbose_name='Recomendações')),
                ('conclusao', models.TextField(blank=True, verbose_name='Conclusão')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EMITIDO', 'Emitido'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=10)),
                ('data_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Data de emissão')),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laudos', to='coletas.inspecao')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laudos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável técnico')),
            ],
            options={
                'verbose_name': 'Laudo',
                'verbose_name_plural': 'Laudos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
