# Generated by Django 5.1.4 on 2026-07-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laudo',
            name='data_medicao_campo',
            field=models.DateField(blank=True, null=True, verbose_name='Medições em campo'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='data_upload_osps',
            field=models.DateField(blank=True, null=True, verbose_name='Upload das OSPs'),
        ),
        migrations.AddField(
            model_name='laudo',
            name='data_upload_relatorio',
            field=models.DateField(blank=True, null=True, verbose_name='Upload do relatório completo'),
        ),
        migrations.AlterField(
            model_name='laudo',
            name='numero',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='Número do laudo'),
        ),
    ]
