# Generated by Django 5.1.4 on 2026-06-22 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_analise', models.CharField(choices=[('VIBRACAO', 'Análise de Vibração'), ('TERMOGRAFIA', 'Termografia Infravermelha'), ('FLUIDOS', 'Análise de Fluidos'), ('ENSAIO_ELETRICO', 'Ensaios Elétricos'), ('ULTRASSOM', 'Ultrassom'), ('ESPESSURA', 'Medição de Espessura'), ('QUALIDADE_ENERGIA', 'Qualidade de Energia'), ('SENSITIVA', 'Inspeção Sensitiva')], default='VIBRACAO', max_length=20)),
                ('data', models.DateField(verbose_name='Data da inspeção')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('CONCLUIDA', 'Concluída')], default='ABERTA', max_length=12)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='cadastros.cliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to=settings.AUTH_USER_MODEL, verbose_name='Técnico/Analista responsável')),
            ],
            options={
                'verbose_name': 'Inspeção',
                'verbose_name_plural': 'Inspeções',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicaoVibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ponto_medicao', models.CharField(help_text='Ex.: Mancal LA', max_length=80, verbose_name='Ponto de medição')),
                ('direcao', models.CharField(choices=[('H', 'Horizontal'), ('V', 'Vertical'), ('A', 'Axial')], max_length=1, verbose_name='Direção')),
                ('rotacao_rpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rotação na coleta (RPM)')),
                ('velocidade_rms', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Velocidade RMS (mm/s)')),
                ('aceleracao_rms', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Aceleração RMS (g)')),
                ('deslocamento_pp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Deslocamento pico-a-pico (µm)')),
                ('fator_crista', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fator de crista')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Temperatura no ponto (°C)')),
                ('zona_iso', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Zona ISO')),
                ('criticidade', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico')], editable=False, max_length=8, verbose_name='Criticidade')),
                ('diagnostico_sugerido', models.TextField(blank=True, editable=False, verbose_name='Diagnóstico sugerido')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora da medição')),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_vibracao', to='cadastros.componente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_vibracao', to='cadastros.equipamento')),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_vibracao', to='coletas.inspecao')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_vibracao', to='cadastros.instrumento')),
            ],
            options={
                'verbose_name': 'Medição de vibração',
                'verbose_name_plural': 'Medições de vibração',
                'ordering': ['-data_hora'],
            },
        ),
    ]
