# Generated by Django 5.1.4 on 2026-06-23 01:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_classificacaoinspecao_falharecorrente_grupoacesso_and_more'),
        ('coletas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicaoTermografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ponto_medicao', models.CharField(help_text='Ex.: Conexão fase R', max_length=80, verbose_name='Ponto de medição')),
                ('sistema', models.CharField(choices=[('ELETRICO', 'Sistemas Elétricos'), ('MEC_DINAMICO', 'Sistemas Mecânicos Dinâmicos'), ('MEC_ESTATICO', 'Sistemas Mecânicos Estáticos'), ('PROCESSO', 'Processos Industriais')], default='ELETRICO', max_length=15, verbose_name='Sistema')),
                ('temperatura_ponto', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Temperatura do ponto (°C)')),
                ('temperatura_referencia', models.DecimalField(decimal_places=1, help_text='Ponto similar saudável (ou fase equivalente).', max_digits=6, verbose_name='Temperatura de referência (°C)')),
                ('temperatura_ambiente', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Temperatura ambiente (°C)')),
                ('emissividade', models.DecimalField(decimal_places=2, default=Decimal('0.95'), max_digits=4, verbose_name='Emissividade')),
                ('carga_percentual', models.DecimalField(blank=True, decimal_places=1, help_text='Carga no momento da medição (sistemas elétricos).', max_digits=5, null=True, verbose_name='Carga (%)')),
                ('delta_t', models.DecimalField(decimal_places=1, editable=False, max_digits=6, verbose_name='ΔT (°C)')),
                ('criticidade', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico')], editable=False, max_length=8, verbose_name='Criticidade')),
                ('diagnostico_sugerido', models.TextField(blank=True, editable=False, verbose_name='Diagnóstico sugerido')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora da medição')),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_termografia', to='cadastros.componente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_termografia', to='cadastros.equipamento')),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_termografia', to='coletas.inspecao')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_termografia', to='cadastros.instrumento')),
            ],
            options={
                'verbose_name': 'Medição de termografia',
                'verbose_name_plural': 'Medições de termografia',
                'ordering': ['-data_hora'],
            },
        ),
    ]
