# Generated by Django 5.1.4 on 2026-06-23 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_classificacaoinspecao_falharecorrente_grupoacesso_and_more'),
        ('coletas', '0002_medicaotermografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecao',
            name='tipo_analise',
            field=models.CharField(choices=[('VIBRACAO', 'Análise de Vibração'), ('TERMOGRAFIA', 'Termografia Infravermelha'), ('FLUIDOS', 'Análise de Fluidos'), ('ENSAIO_ELETRICO', 'Ensaios Elétricos'), ('ULTRASSOM', 'Ultrassom'), ('ESPESSURA', 'Medição de Espessura'), ('QUALIDADE_ENERGIA', 'Qualidade de Energia'), ('SENSITIVA', 'Inspeção Sensitiva'), ('CORRETIVA', 'Manutenção Corretiva')], default='VIBRACAO', max_length=20),
        ),
        migrations.CreateModel(
            name='MedicaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('VIBRACAO', 'Análise de Vibração'), ('TERMOGRAFIA', 'Termografia Infravermelha'), ('FLUIDOS', 'Análise de Fluidos'), ('ENSAIO_ELETRICO', 'Ensaios Elétricos'), ('ULTRASSOM', 'Ultrassom'), ('ESPESSURA', 'Medição de Espessura'), ('QUALIDADE_ENERGIA', 'Qualidade de Energia'), ('SENSITIVA', 'Inspeção Sensitiva'), ('CORRETIVA', 'Manutenção Corretiva')], max_length=20, verbose_name='Tipo de análise')),
                ('ponto_medicao', models.CharField(max_length=80, verbose_name='Ponto de medição')),
                ('grandeza', models.CharField(help_text='Ex.: Resistência de isolação', max_length=80, verbose_name='Grandeza medida')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Valor')),
                ('unidade', models.CharField(blank=True, max_length=20, verbose_name='Unidade')),
                ('valor_referencia', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valor de referência')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='Parâmetros adicionais')),
                ('criticidade', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico')], editable=False, max_length=8)),
                ('diagnostico_sugerido', models.TextField(blank=True, editable=False, verbose_name='Diagnóstico sugerido')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora da medição')),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_tecnicas', to='cadastros.componente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_tecnicas', to='cadastros.equipamento')),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_tecnicas', to='coletas.inspecao')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_tecnicas', to='cadastros.instrumento')),
            ],
            options={
                'verbose_name': 'Medição técnica',
                'verbose_name_plural': 'Medições técnicas',
                'ordering': ['-data_hora'],
            },
        ),
    ]
