# Generated by Django 5.1.4 on 2026-07-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0003_alter_inspecao_tipo_analise_medicaotecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaovibracao',
            name='numero_mancal',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1, 2, 3… conforme a numeração do croqui.', null=True, verbose_name='Nº do mancal'),
        ),
        migrations.AddField(
            model_name='medicaovibracao',
            name='parametro',
            field=models.CharField(blank=True, choices=[('A', 'Aceleração'), ('V', 'Velocidade'), ('E', 'Envelope'), ('D', 'Demodulação')], max_length=1, verbose_name='Parâmetro'),
        ),
    ]
