# Generated by Django 5.1.4 on 2026-08-05 03:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_condicao'),
        ('coletas', '0004_medicaovibracao_numero_mancal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('componente_texto', models.CharField(blank=True, help_text='Ex.: DJ5', max_length=120, verbose_name='Componente (texto)')),
                ('detalhe', models.CharField(blank=True, help_text='Uso interno (ex.: nº da imagem no termovisor) — não sai para o cliente.', max_length=200, verbose_name='Detalhe do componente')),
                ('anomalia_texto', models.TextField(blank=True, verbose_name='Anomalia (texto)')),
                ('recomendacao_texto', models.TextField(blank=True, verbose_name='Recomendação (texto)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('aceleracao_global', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Global de aceleração (g)')),
                ('velocidade_global', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Global de velocidade (mm/s)')),
                ('temperatura_medida', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Temperatura medida (°C)')),
                ('temperatura_referencia', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Temperatura de referência (°C)')),
                ('delta_t', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=6, null=True, verbose_name='ΔT (°C)')),
                ('carga_percentual', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Carga (%)')),
                ('temperatura_medida_corrigida', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=6, null=True)),
                ('temperatura_referencia_corrigida', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=6, null=True)),
                ('delta_t_corrigido', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=6, null=True)),
                ('corrente_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('corrente_a', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('corrente_b', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('corrente_c', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('tensao_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('tensao_a', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('tensao_b', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('tensao_c', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('numero_osp', models.CharField(blank=True, max_length=40, verbose_name='Número da OSP')),
                ('confirmada', models.BooleanField(default=False, verbose_name='Confirmada no escritório')),
                ('visivel_cliente', models.BooleanField(default=False, verbose_name='Visível para o cliente')),
                ('grau_risco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achados', to='cadastros.tipocriticidade', verbose_name='Grau de risco')),
                ('recomendacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achados', to='cadastros.tiporecomendacao')),
                ('tipo_anomalia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achados', to='cadastros.tipoanomalia')),
                ('tipo_componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achados', to='cadastros.tipocomponente')),
            ],
            options={
                'verbose_name': 'Achado / análise',
                'verbose_name_plural': 'Achados / análises',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AchadoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('REAL', 'Foto real'), ('TERMICA', 'Imagem térmica'), ('TENDENCIA', 'Linha de tendência'), ('ESPECTRO', 'Espectro')], max_length=12, verbose_name='Tipo de imagem')),
                ('arquivo', models.ImageField(upload_to='achados/', verbose_name='Arquivo')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('achado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='coletas.achado')),
            ],
            options={
                'verbose_name': 'Imagem do achado',
                'verbose_name_plural': 'Imagens dos achados',
                'ordering': ['tipo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Carregamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('numero_relatorio', models.CharField(blank=True, max_length=40, verbose_name='Número do relatório')),
                ('status', models.CharField(choices=[('EM_CAMPO', 'Em campo'), ('TRANSFERIDA', 'Transferida'), ('DESCARTADA', 'Descartada')], default='EM_CAMPO', max_length=12)),
                ('transferido_em', models.DateTimeField(blank=True, null=True, verbose_name='Transferido em')),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carregamentos', to=settings.AUTH_USER_MODEL, verbose_name='Analista responsável')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carregamentos', to='cadastros.cliente')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carregamentos', to='cadastros.instrumento')),
                ('rota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carregamentos', to='cadastros.rota')),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carregamentos', to='cadastros.tecnologiaanalise', verbose_name='Tecnologia')),
            ],
            options={
                'verbose_name': 'Carregamento de rota',
                'verbose_name_plural': 'Carregamentos de rota',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemInspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem')),
                ('carregamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='coletas.carregamento')),
                ('condicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='cadastros.condicao')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inspecao', to='cadastros.equipamento')),
            ],
            options={
                'verbose_name': 'Item de inspeção',
                'verbose_name_plural': 'Itens de inspeção',
                'ordering': ['ordem', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='achado',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achados', to='coletas.iteminspecao'),
        ),
    ]
