# Generated by Django 5.1.4 on 2026-08-06 08:57
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.utils import timezone


def migrar_para_relatorio(apps, schema_editor):
    """
    Preserva carregamentos existentes: cria um Relatorio a partir do antigo
    numero_relatorio/data e vincula o carregamento (deduplicando por número).
    """
    Carregamento = apps.get_model("coletas", "Carregamento")
    Relatorio = apps.get_model("coletas", "Relatorio")
    for c in Carregamento.objects.all():
        data = c.data or timezone.localdate()
        numero = (c.numero_relatorio or "").strip() or f"{data.strftime('%Y%m%d')}-001"
        rel = Relatorio.objects.filter(cliente_id=c.cliente_id, numero=numero).first()
        if rel is None:
            rel = Relatorio.objects.create(
                cliente_id=c.cliente_id,
                tecnologia_id=c.tecnologia_id,
                numero=numero,
                data_inicio=data,
                data_termino=data,
            )
        c.relatorio_id = rel.id
        c.data_coleta = data
        c.save(update_fields=["relatorio_id", "data_coleta"])


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_condicao'),
        ('coletas', '0005_achado_achadoimagem_carregamento_iteminspecao_and_more'),
    ]

    operations = [
        # 1) Cria a estrutura nova (colunas/tabela) mantendo as antigas.
        migrations.AddField(
            model_name='carregamento',
            name='data_coleta',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de coleta'),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.CharField(max_length=40, verbose_name='Número do relatório')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_termino', models.DateField(verbose_name='Data de término (auditoria)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to='cadastros.cliente')),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to='cadastros.tecnologiaanalise', verbose_name='Tecnologia')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='carregamento',
            name='relatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carregamentos', to='coletas.relatorio'),
        ),
        # 2) Migra os dados existentes para a nova estrutura.
        migrations.RunPython(migrar_para_relatorio, migrations.RunPython.noop),
        # 3) Aplica a restrição e remove as colunas antigas.
        migrations.AddConstraint(
            model_name='relatorio',
            constraint=models.UniqueConstraint(fields=('cliente', 'numero'), name='uniq_relatorio_cliente_numero'),
        ),
        migrations.RemoveField(
            model_name='carregamento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='carregamento',
            name='numero_relatorio',
        ),
    ]
