# Generated by Django 5.1.4 on 2026-08-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_condicao_options_condicao_sigla'),
        ('coletas', '0006_remove_carregamento_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achado',
            name='grau_risco',
        ),
        migrations.AddField(
            model_name='achado',
            name='condicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achados', to='cadastros.condicao', verbose_name='Condição / grau de risco'),
        ),
    ]
