# Generated by Django 5.1.4 on 2026-08-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0007_remove_achado_grau_risco_achado_condicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='consideracoes_finais',
            field=models.TextField(blank=True, verbose_name='Considerações finais'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='data_finalizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de finalização do relatório'),
        ),
    ]
