# Generated by Django 5.1.4 on 2026-09-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0009_relatorio_numero_hifen'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregamento',
            name='tipo_corretiva',
            field=models.CharField(blank=True, choices=[('BALANCEAMENTO', 'Balanceamento dinâmico em campo'), ('ALINHAMENTO', 'Alinhamento a laser')], default='', max_length=15),
        ),
    ]
