# Generated by Django 5.1.4 on 2026-10-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0010_carregamento_tipo_corretiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='achado',
            name='deslocamento_global',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Global de deslocamento (µm RMS)'),
        ),
    ]
