# Generated by Django 5.1.4 on 2026-06-23 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('interno', models.BooleanField(default=True, verbose_name='Alertas internos')),
                ('email', models.BooleanField(default=True, verbose_name='E-mail')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='WhatsApp')),
                ('push', models.BooleanField(default=False, verbose_name='Push')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pref_notificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência de notificação',
                'verbose_name_plural': 'Preferências de notificação',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('evento', models.CharField(choices=[('NOVA_OSP', 'Nova OSP'), ('EQUIPAMENTO_CRITICO', 'Equipamento crítico'), ('LAUDO_CONCLUIDO', 'Laudo concluído'), ('SLA_VENCENDO', 'SLA vencendo'), ('APROVACAO_PENDENTE', 'Aprovação pendente')], max_length=24)),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='Link (rota do frontend)')),
                ('nivel', models.CharField(choices=[('INFO', 'Informativo'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico')], default='ALERTA', max_length=8)),
                ('canais_enviados', models.JSONField(blank=True, default=list, verbose_name='Canais despachados')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('lida_em', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['destinatario', 'lida'], name='notificacoe_destina_87c32f_idx')],
            },
        ),
    ]
