# Generated by Django 5.1.4 on 2026-06-23 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_classificacaoinspecao_falharecorrente_grupoacesso_and_more'),
        ('coletas', '0002_medicaotermografia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número da OSP')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=8)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em análise'), ('EM_EXECUCAO', 'Em execução'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('criticidade_origem', models.CharField(blank=True, max_length=8, verbose_name='Criticidade de origem')),
                ('gerada_automaticamente', models.BooleanField(default=False, verbose_name='Gerada automaticamente')),
                ('sla_data', models.DateField(blank=True, null=True, verbose_name='Prazo (SLA)')),
                ('finalizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='osps', to='cadastros.cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='osps', to='cadastros.equipamento')),
                ('inspecao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osps', to='coletas.inspecao')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osps', to=settings.AUTH_USER_MODEL, verbose_name='Técnico responsável')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço Preditiva',
                'verbose_name_plural': 'Ordens de Serviço Preditivas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
