# Generated by Django 5.1.4 on 2026-06-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='custo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo estimado (R$)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='custo_real',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Custo real (R$)'),
        ),
    ]
