# Generated by Django 5.1.4 on 2026-07-23 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osp', '0002_ordemservico_custo_estimado_ordemservico_custo_real'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='amplitude_aceleracao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amplitude aceleração global (mm/s²)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='amplitude_velocidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amplitude velocidade global (mm/s)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='anomalia',
            field=models.TextField(blank=True, verbose_name='Anomalia detectada'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='componente',
            field=models.CharField(blank=True, max_length=120, verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='descricao_corretiva',
            field=models.TextField(blank=True, help_text='O que a equipe de manutenção efetivamente fez.', verbose_name='Descrição da corretiva executada'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='emerg_mao_obra_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Emergencial — mão de obra (h)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='emerg_mao_obra_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Emergencial — mão de obra (R$)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='emerg_material_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Emergencial — material de reparo (R$)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='emerg_outros_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Emergencial — outros (R$)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='emerg_producao_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Emergencial — produção (h/ton)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='emerg_producao_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Emergencial — produção (R$)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='emerg_terceirizado_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Emergencial — serviço terceirizado (h)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='emerg_terceirizado_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Emergencial — serviço terceirizado (R$)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='executado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Corretiva em'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='executado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osps_executadas', to=settings.AUTH_USER_MODEL, verbose_name='Corretiva por'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='finalizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osps_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Finalização por'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='grau_risco',
            field=models.CharField(blank=True, choices=[('GR0', 'GR-0 — Sem anomalia'), ('GR1', 'GR-1 — Risco eminente'), ('GR2', 'GR-2 — Risco elevado'), ('GR3', 'GR-3 — Risco moderado'), ('GR4', 'GR-4 — Risco baixo')], help_text='Define o prazo de correção (GR-1: 3d, GR-2: 10d, GR-3: 20d, GR-4: 30d).', max_length=3, verbose_name='Grau de risco'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='planejado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planejamento em'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='planejado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osps_planejadas', to=settings.AUTH_USER_MODEL, verbose_name='Planejamento por'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pred_mao_obra_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preditiva — mão de obra (h)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pred_mao_obra_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preditiva — mão de obra (R$)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pred_material_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preditiva — material de reparo (R$)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pred_outros_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preditiva — outros (R$)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pred_producao_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preditiva — produção (h/ton)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pred_producao_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preditiva — produção (R$)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pred_terceirizado_h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preditiva — serviço terceirizado (h)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pred_terceirizado_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Preditiva — serviço terceirizado (R$)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='recomendacao',
            field=models.TextField(blank=True, verbose_name='Recomendação'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('PLANEJADA', 'Planejada'), ('EXECUTADA', 'Executada'), ('EM_ANALISE', 'Em análise'), ('EM_EXECUCAO', 'Em execução'), ('AGUARDANDO_APROVACAO', 'Aguardando aprovação'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20),
        ),
    ]
