# Generated by Django 5.1.4 on 2026-07-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osp', '0003_ordemservico_amplitude_aceleracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='acompanhamento',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('CORRIGIDA', 'Corrigida'), ('REINCIDENTE', 'Reincidente'), ('NAO_REAVALIADA', 'Não reavaliada'), ('RETORNO_INFO', 'Retorno de informação')], default='ABERTA', help_text='Situação da anomalia na reavaliação seguinte (gráfico Controle das OSPs).', max_length=15, verbose_name='Acompanhamento'),
        ),
    ]
