# Generated by Django 5.1.4 on 2026-07-23 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_instrumento_periodicidade_calibracao'),
        ('osp', '0004_ordemservico_acompanhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_anomalia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osps', to='cadastros.tipoanomalia', verbose_name='Tipo de anomalia'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osps', to='cadastros.tipocomponente', verbose_name='Tipo de componente'),
        ),
    ]
