# Generated by Django 5.1.4 on 2026-08-08 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0007_remove_achado_grau_risco_achado_condicao'),
        ('osp', '0005_ordemservico_tipo_anomalia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='achado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osp', to='coletas.achado'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='sequencial_cliente',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Sequencial da OSP (por cliente)'),
        ),
    ]
