# Generated by Django 5.1.4 on 2026-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osp', '0007_ordemservico_sequencial_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='resultado_confirmacao',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando confirmação'), ('CONFIRMADO', 'Confirmado — diagnóstico correto'), ('NAO_CONFIRMADO', 'Não confirmado — diagnóstico divergente')], default='PENDENTE', help_text='A abertura da máquina confirmou o que a preditiva apontou?', max_length=15, verbose_name='Confirmação do diagnóstico'),
        ),
    ]
