# Generated by Django 5.1.4 on 2026-10-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osp', '0008_ordemservico_resultado_confirmacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='amplitude_deslocamento',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Amplitude deslocamento global (µm RMS)'),
        ),
    ]
