# Generated by Django 5.1.4 on 2026-06-22 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome da empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('unidade_negocio', models.CharField(blank=True, max_length=120, verbose_name='Unidade de negócio')),
                ('cidade_uf', models.CharField(blank=True, max_length=80, verbose_name='Cidade/UF')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('contato_gestor', models.CharField(blank=True, max_length=120, verbose_name='Contato gestor')),
                ('departamento', models.CharField(blank=True, max_length=120, verbose_name='Departamento')),
                ('logomarca', models.ImageField(blank=True, null=True, upload_to='logos/clientes/', verbose_name='Logomarca')),
            ],
            options={
                'verbose_name': 'Cliente (contratante)',
                'verbose_name_plural': 'Clientes (contratantes)',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome da empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('cidade_uf', models.CharField(blank=True, max_length=80, verbose_name='Cidade/UF')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('contato_gestor', models.CharField(blank=True, max_length=120, verbose_name='Contato gestor')),
                ('departamento', models.CharField(blank=True, max_length=120, verbose_name='Departamento')),
                ('logomarca', models.ImageField(blank=True, null=True, upload_to='logos/empresas/', verbose_name='Logomarca')),
            ],
            options={
                'verbose_name': 'Empresa (contratada)',
                'verbose_name_plural': 'Empresas (contratadas)',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tag', models.CharField(help_text='Identificação no campo (ex.: BBA-101)', max_length=60, verbose_name='TAG')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome/Descrição')),
                ('tipo', models.CharField(blank=True, max_length=80, verbose_name='Tipo de equipamento')),
                ('fabricante', models.CharField(blank=True, max_length=80, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=80, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=80, verbose_name='Número de série')),
                ('potencia_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Potência (kW)')),
                ('rotacao_nominal_rpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rotação nominal (RPM)')),
                ('classe_iso', models.CharField(choices=[('I', 'Classe I (≤15 kW)'), ('II', 'Classe II (15–75 kW)'), ('III', 'Classe III (base rígida)'), ('IV', 'Classe IV (base flexível)')], default='II', help_text='Define os limiares de severidade da análise de vibração.', max_length=3, verbose_name='Classe ISO (vibração)')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(max_length=80, verbose_name='Tipo de instrumento')),
                ('marca', models.CharField(blank=True, max_length=80, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=80, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=80, verbose_name='Número de série')),
                ('data_ultima_calibracao', models.DateField(blank=True, null=True, verbose_name='Última calibração')),
                ('entidade_calibracao', models.CharField(blank=True, max_length=120, verbose_name='Entidade de calibração')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=120, verbose_name='Área')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='cadastros.cliente')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['-criado_em'],
                'abstract': False,
                'unique_together': {('cliente', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(help_text='Ex.: Mancal LA, Mancal LOA', max_length=120, verbose_name='Componente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='cadastros.equipamento')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=120, verbose_name='Setor')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='cadastros.area')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['-criado_em'],
                'abstract': False,
                'unique_together': {('area', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='cadastros.setor'),
        ),
        migrations.AlterUniqueTogether(
            name='equipamento',
            unique_together={('setor', 'tag')},
        ),
    ]
