# Generated by Django 5.1.4 on 2026-07-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_classificacaoinspecao_falharecorrente_grupoacesso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='normas', to='cadastros.tecnologiaanalise', verbose_name='Tecnologias aplicáveis'),
        ),
    ]
