# Generated by Django 5.1.4 on 2026-07-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_norma_tecnologias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoanomalia',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='tipos_anomalia', to='cadastros.tecnologiaanalise', verbose_name='Tecnologias aplicáveis'),
        ),
        migrations.AddField(
            model_name='tipocomponente',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='tipos_componente', to='cadastros.tecnologiaanalise', verbose_name='Tecnologias aplicáveis'),
        ),
        migrations.AddField(
            model_name='tiporecomendacao',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='tipos_recomendacao', to='cadastros.tecnologiaanalise', verbose_name='Tecnologias aplicáveis'),
        ),
    ]
