# Generated by Django 5.1.4 on 2026-07-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_tipoanomalia_tecnologias_tipocomponente_tecnologias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacaoinspecao',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='falharecorrente',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='grupoacesso',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='norma',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tecnologiaanalise',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipoanomalia',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipocomponente',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipocriticidade',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipoequipamento',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipoinspecao',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tiporecomendacao',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
    ]
