# Generated by Django 5.1.4 on 2026-07-22 23:49

from django.db import migrations, models


def migrar_endereco_legado(apps, schema_editor):
    """
    Preserva o que já foi cadastrado antes do endereço virar campos separados:
    'endereco' vira o logradouro e 'cidade_uf' (ex.: "Campinas/SP") é dividido
    em cidade + UF. Roda ANTES de remover a coluna antiga.
    """
    for modelo in ("Cliente", "Empresa"):
        Model = apps.get_model("cadastros", modelo)
        for obj in Model.objects.all().iterator():
            mudou = False
            if getattr(obj, "endereco", "") and not obj.logradouro:
                obj.logradouro = obj.endereco[:200]
                mudou = True
            if obj.cidade_uf and not obj.cidade:
                partes = obj.cidade_uf.rsplit("/", 1)
                obj.cidade = partes[0].strip()[:100]
                if len(partes) == 2:
                    obj.uf = partes[1].strip()[:2].upper()
                mudou = True
            if mudou:
                obj.save(update_fields=["logradouro", "cidade", "uf"])


def reverter(apps, schema_editor):
    """Sem volta: as colunas novas somem ao desfazer a migração."""


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_classificacaoinspecao_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente (contratante)', 'verbose_name_plural': 'Clientes (contratantes)'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=160, verbose_name='Nome fantasia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, help_text='Somente números ou 00000-000', max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade_uf',
            field=models.CharField(blank=True, editable=False, max_length=80, verbose_name='Cidade/UF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=160, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, help_text='Somente números ou 00000-000', max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cidade_uf',
            field=models.CharField(blank=True, editable=False, max_length=80, verbose_name='Cidade/UF'),
        ),
        # Copia os dados antigos para os campos novos ANTES de apagar a coluna.
        migrations.RunPython(migrar_endereco_legado, reverter),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='endereco',
        ),
    ]
