# Generated by Django 5.1.4 on 2026-07-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_cliente_options_remove_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['codigo', 'nome'], 'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['codigo', 'nome'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AddField(
            model_name='area',
            name='codigo',
            field=models.CharField(blank=True, help_text='Ex.: 001', max_length=20, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='area',
            name='complemento',
            field=models.CharField(blank=True, help_text='Ex.: Matriz, Filial', max_length=120, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='periodicidade_calibracao',
            field=models.PositiveSmallIntegerField(choices=[(12, 'Anual'), (24, 'Bienal'), (36, 'Trienal')], default=24, verbose_name='Validade da calibração'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='software_analise',
            field=models.CharField(blank=True, help_text='Ex.: OMNITREND', max_length=120, verbose_name='Software de análise'),
        ),
        migrations.AddField(
            model_name='setor',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='setor',
            name='complemento',
            field=models.CharField(blank=True, help_text='Ex.: Piso Inferior', max_length=120, verbose_name='Complemento'),
        ),
    ]
