# Generated by Django 5.1.4 on 2026-07-23 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_area_options_alter_setor_options_area_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='equipamento_pai',
            field=models.ForeignKey(blank=True, help_text='Preencha apenas se este for um sub-item (ex.: exaustor de uma caldeira).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitens', to='cadastros.equipamento', verbose_name='Equipamento principal'),
        ),
    ]
