# Generated by Django 5.1.4 on 2026-07-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_equipamento_equipamento_pai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='periodicidade_calibracao',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Semestral'), (12, 'Anual'), (24, 'Bienal'), (36, 'Trienal')], default=24, verbose_name='Validade da calibração'),
        ),
    ]
