# Generated by Django 5.1.4 on 2026-07-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_instrumento_periodicidade_calibracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='instrumentos', to='cadastros.tecnologiaanalise', verbose_name='Tecnologias aplicáveis'),
        ),
    ]
