# Generated by Django 5.1.4 on 2026-07-31 02:35

import django.db.models.deletion
from django.db import migrations, models


def vincular_tipo_existente(apps, schema_editor):
    """
    Converte o texto livre já cadastrado em vínculo com o catálogo:
    para cada equipamento com `tipo` preenchido, encontra (ou cria) o
    TipoEquipamento com aquele nome e liga a FK. Preserva os dados atuais.
    """
    Equipamento = apps.get_model("cadastros", "Equipamento")
    TipoEquipamento = apps.get_model("cadastros", "TipoEquipamento")
    for eq in Equipamento.objects.exclude(tipo="").filter(tipo_equipamento__isnull=True):
        nome = eq.tipo.strip()
        if not nome:
            continue
        tipo = TipoEquipamento.objects.filter(nome__iexact=nome).first()
        if tipo is None:
            tipo = TipoEquipamento.objects.create(nome=nome)
        eq.tipo_equipamento = tipo
        eq.save(update_fields=["tipo_equipamento"])


def reverter(apps, schema_editor):
    """Sem volta: o campo texto `tipo` foi preservado, então nada a desfazer."""


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_instrumento_tecnologias'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tipo_equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='cadastros.tipoequipamento', verbose_name='Tipo de equipamento'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(blank=True, max_length=80, verbose_name='Tipo (texto)'),
        ),
        migrations.RunPython(vincular_tipo_existente, reverter),
    ]
