# Generated by Django 5.1.4 on 2026-07-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_equipamento_tipo_equipamento_alter_equipamento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='criticidade',
            field=models.CharField(blank=True, choices=[('A', 'A — Alta (crítico ao processo)'), ('B', 'B — Média (importante)'), ('C', 'C — Baixa (auxiliar)')], help_text='Classificação A/B/C da importância no processo produtivo.', max_length=1, verbose_name='Criticidade (importância)'),
        ),
    ]
