# Generated by Django 5.1.4 on 2026-07-31 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_equipamento_criticidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='tecnologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas', to='cadastros.tecnologiaanalise', verbose_name='Tecnologia'),
        ),
    ]
