# Generated by Django 5.1.4 on 2026-08-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_rota_tecnologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('gera_acao', models.BooleanField(default=False, help_text='Se marcado, selecionar esta condição exige registrar uma análise no campo.', verbose_name='Gera análise')),
                ('cor', models.CharField(default='#64748b', help_text='Ex.: #22c55e', max_length=7, verbose_name='Cor (hex)')),
                ('nivel', models.PositiveSmallIntegerField(default=0, help_text='Ordem de severidade (0 = menor).', verbose_name='Nível')),
            ],
            options={
                'verbose_name': 'Condição',
                'verbose_name_plural': 'Condições',
                'ordering': ['nivel', 'nome'],
                'abstract': False,
            },
        ),
    ]
