# Generated by Django 5.1.4 on 2026-08-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_condicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicao',
            options={'ordering': ['nivel', 'nome'], 'verbose_name': 'Condição do equipamento', 'verbose_name_plural': 'Condições do equipamento'},
        ),
        migrations.AddField(
            model_name='condicao',
            name='sigla',
            field=models.CharField(blank=True, help_text='Ex.: OK, PDP, PDM, IC, GR0…', max_length=20, verbose_name='Sigla'),
        ),
    ]
