# Generated by Django 5.1.4 on 2026-08-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_condicao_options_condicao_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologiaanalise',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='tecnologias/', verbose_name='Imagem/ícone'),
        ),
    ]
