# Generated by Django 5.1.4 on 2026-08-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_tecnologiaanalise_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='site',
            field=models.CharField(blank=True, help_text='Ex.: thermoproactive.com.br', max_length=120, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefone'),
        ),
    ]
