# Generated by Django 5.1.4 on 2026-08-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_empresa_email_empresa_site_empresa_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='inscricao_estadual',
            field=models.CharField(blank=True, help_text='Ex.: Isenta', max_length=30, verbose_name='Inscrição estadual'),
        ),
    ]
