# Generated by Django 5.1.4 on 2026-08-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_empresa_inscricao_estadual'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologiaanalise',
            name='definicao_tecnica',
            field=models.TextField(blank=True, help_text='Texto/fluxo de trabalho que sai no item 7 da carta.', verbose_name='Definição da técnica'),
        ),
        migrations.AddField(
            model_name='tecnologiaanalise',
            name='imagem_pontos_medicao',
            field=models.ImageField(blank=True, null=True, upload_to='tecnologias/pontos/', verbose_name='Imagem dos pontos de medição'),
        ),
    ]
