# Generated by Django 5.1.4 on 2026-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_tecnologiaanalise_definicao_tecnica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologiaanalise',
            name='definicao_fluxo_trabalho',
            field=models.TextField(blank=True, help_text="Uma etapa por linha (ex.: '1ª etapa (contratada): …').", verbose_name='Definição da técnica — etapas do fluxo de trabalho'),
        ),
        migrations.AddField(
            model_name='tecnologiaanalise',
            name='definicao_legenda_imagem',
            field=models.CharField(blank=True, help_text='Frase antes da imagem dos pontos de medição.', max_length=200, verbose_name='Definição da técnica — legenda da imagem'),
        ),
        migrations.AlterField(
            model_name='tecnologiaanalise',
            name='definicao_tecnica',
            field=models.TextField(blank=True, help_text='Parágrafos de abertura do item 7 (um por linha).', verbose_name='Definição da técnica — texto introdutório'),
        ),
    ]
