# Generated by Django 5.1.4 on 2026-09-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_seed_definicao_vibracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologiaanalise',
            name='tipo_corretiva',
            field=models.CharField(blank=True, choices=[('BALANCEAMENTO', 'Balanceamento dinâmico em campo'), ('ALINHAMENTO', 'Alinhamento a laser')], default='', max_length=15, verbose_name='Análise corretiva'),
        ),
    ]
