# Generated by Django 5.1.4 on 2026-09-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_tecnologiaanalise_tipo_corretiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporecomendacao',
            name='anomalias',
            field=models.ManyToManyField(blank=True, related_name='recomendacoes', to='cadastros.tipoanomalia', verbose_name='Anomalias compatíveis'),
        ),
    ]
