# Generated by Django 5.1.4 on 2026-09-10 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_tiporecomendacao_anomalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='fator_potencia_nominal',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Da placa de identificação do motor.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Fator de potência nominal'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tensao_nominal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Da placa de identificação do motor.', max_digits=8, null=True, verbose_name='Tensão nominal (V)'),
        ),
    ]
