# Generated by Django 5.1.4 on 2026-09-10 11:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_equipamento_fator_potencia_nominal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipamento',
            name='categoria_tecnica',
            field=models.CharField(blank=True, choices=[('MOTOR_ELETRICO', 'Motor elétrico'), ('TRANSFORMADOR', 'Transformador')], default='', help_text='Define qual datasheet técnico específico (motor, transformador…) os equipamentos deste tipo podem ter. Vazio = sem datasheet específico.', max_length=20, verbose_name='Categoria técnica'),
        ),
        migrations.CreateModel(
            name='DadosTecnicosMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('potencia_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Potência (kW)')),
                ('tensao_v', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tensão (V)')),
                ('corrente_a', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Corrente (A)')),
                ('rotacao_rpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rotação (RPM)')),
                ('fator_potencia', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Fator de potência (FP)')),
                ('fator_servico', models.DecimalField(blank=True, decimal_places=2, help_text='Ex.: 1,15 — margem de sobrecarga contínua admissível pela placa.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fator de serviço (FS)')),
                ('classe_isolacao', models.CharField(blank=True, help_text='Convenção da placa (ex.: A, B, E, F, H) — texto livre, não é código fechado.', max_length=4, verbose_name='Classe de isolação (ISOL)')),
                ('rendimento_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Rendimento (%)')),
                ('rolamento_loa', models.CharField(blank=True, max_length=40, verbose_name='Rolamento LOA (lado oposto ao acoplamento)')),
                ('rolamento_la', models.CharField(blank=True, max_length=40, verbose_name='Rolamento LA (lado do acoplamento)')),
                ('tipo_base', models.CharField(blank=True, choices=[('RIGIDA', 'Rígida'), ('FLEXIVEL', 'Flexível')], help_text='Rígida ou flexível — decide a Classe ISO III×IV acima de 75 kW.', max_length=10, verbose_name='Tipo de base')),
                ('foto_placa', models.ImageField(blank=True, null=True, upload_to='equipamentos/placas/motor/', verbose_name='Foto da placa de identificação')),
                ('equipamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_motor', to='cadastros.equipamento')),
            ],
            options={
                'verbose_name': 'Dados técnicos — Motor elétrico',
                'verbose_name_plural': 'Dados técnicos — Motores elétricos',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DadosTecnicosTransformador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('potencia_kva', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Potência (kVA)')),
                ('tensao_primaria_v', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Tensão primária (V)')),
                ('tensao_secundaria_v', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Tensão secundária (V)')),
                ('impedancia_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Impedância (%)')),
                ('grupo_ligacao', models.CharField(blank=True, help_text='Ex.: Dyn1.', max_length=20, verbose_name='Grupo de ligação')),
                ('foto_placa', models.ImageField(blank=True, null=True, upload_to='equipamentos/placas/transformador/', verbose_name='Foto da placa de identificação')),
                ('equipamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_transformador', to='cadastros.equipamento')),
            ],
            options={
                'verbose_name': 'Dados técnicos — Transformador',
                'verbose_name_plural': 'Dados técnicos — Transformadores',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
    ]
