# Generated by Django 5.1.4 on 2026-09-24 23:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_tecnologiaanalise_modulo_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadostecnicostransformador',
            name='possui_tanque_expansao',
            field=models.BooleanField(blank=True, null=True, verbose_name='Possui tanque de expansão'),
        ),
        migrations.AddField(
            model_name='dadostecnicostransformador',
            name='tensao_secundaria_fase_v',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Tensão secundária de fase (V)'),
        ),
        migrations.AddField(
            model_name='dadostecnicostransformador',
            name='volume_oleo_l',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantidade de óleo (L)'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ano_fabricacao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano de fabricação'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='numero_patrimonio',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número de patrimônio'),
        ),
        migrations.AlterField(
            model_name='tecnologiaanalise',
            name='modulo_tecnico',
            field=models.CharField(blank=True, choices=[('VIBRACAO', 'Vibração'), ('TERMOGRAFIA', 'Termografia'), ('OLEO_ISOLANTE', 'Óleo isolante (transformador)'), ('ENSAIO_ELETRICO', 'Ensaios elétricos (transformador)')], default='', help_text='Medições, imagens e norma que o relatório técnico desta tecnologia mostra. Vazio = layout padrão da inspeção por rota.', max_length=20, verbose_name='Módulo técnico do relatório'),
        ),
    ]
