# Generated by Django 5.1.4 on 2026-10-01 02:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_dadostecnicostransformador_possui_tanque_expansao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipamento',
            name='analise_vibracao',
            field=models.BooleanField(default=False, help_text='Marque nos tipos de máquina rotativa monitorados por análise de vibração: o equipamento passa a ter a classe do critério de severidade. Não se aplica a transformador.', verbose_name='Avaliado por severidade de vibração'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='classe_iso',
            field=models.CharField(blank=True, choices=[('I', 'Classe I (≤15 kW)'), ('II', 'Classe II (15–75 kW)'), ('III', 'Classe III (base rígida)'), ('IV', 'Classe IV (base flexível)')], default='II', help_text='Grupo da máquina no critério de severidade de vibração. Vazio quando o tipo do equipamento não é avaliado por vibração.', max_length=3, verbose_name='Classe ISO (vibração)'),
        ),
        migrations.CreateModel(
            name='CriterioSeveridadeVibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('norma_codigo', models.CharField(help_text='Ex.: ISO 10816-1', max_length=40, verbose_name='Norma')),
                ('norma_edicao', models.CharField(blank=True, help_text='Ex.: 1995', max_length=20, verbose_name='Edição')),
                ('classe', models.CharField(choices=[('I', 'Classe I (≤15 kW)'), ('II', 'Classe II (15–75 kW)'), ('III', 'Classe III (base rígida)'), ('IV', 'Classe IV (base flexível)')], max_length=3, verbose_name='Grupo/classe da máquina')),
                ('suporte', models.CharField(blank=True, choices=[('RIGIDO', 'Rígido'), ('FLEXIVEL', 'Flexível')], help_text='Vazio = vale para qualquer suporte.', max_length=10, verbose_name='Suporte')),
                ('descricao_grupo', models.CharField(blank=True, help_text='Ex.: Máquinas pequenas, até 15 kW', max_length=120, verbose_name='Descrição do grupo')),
                ('limite_ab', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Limite A/B (mm/s RMS)')),
                ('limite_bc', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Limite B/C (mm/s RMS)')),
                ('limite_cd', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Limite C/D (mm/s RMS)')),
                ('origem', models.CharField(choices=[('NORMA', 'Norma (valor publicado)'), ('ACORDO_CLIENTE', 'Acordo com o cliente / contrato'), ('LEGADO', 'Legado (origem não documentada)')], default='NORMA', max_length=15, verbose_name='Origem')),
                ('fonte', models.CharField(blank=True, help_text='Tabela/anexo da norma, ata, contrato ou e-mail que sustenta o valor.', max_length=250, verbose_name='Fonte')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Vigência — início')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Vigência — fim')),
                ('cliente', models.ForeignKey(blank=True, help_text='Vazio = vale para todos os clientes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterios_vibracao', to='cadastros.cliente')),
            ],
            options={
                'verbose_name': 'Critério de severidade de vibração',
                'verbose_name_plural': 'Critérios de severidade de vibração',
                'ordering': ['classe', 'origem', '-vigencia_inicio'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('limite_ab__lte', models.F('limite_bc')), ('limite_bc__lte', models.F('limite_cd'))), name='criterio_vibracao_limites_crescentes')],
            },
        ),
    ]
