# Generated by Django 5.1.4 on 2026-10-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_dados_categoria_vibracao_criterios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologiaanalise',
            name='modulo_tecnico',
            field=models.CharField(blank=True, choices=[('VIBRACAO', 'Vibração'), ('BALANCEAMENTO', 'Balanceamento dinâmico (corretiva)'), ('TERMOGRAFIA', 'Termografia'), ('OLEO_ISOLANTE', 'Óleo isolante (transformador)'), ('ENSAIO_ELETRICO', 'Ensaios elétricos — transformador (TRF)'), ('FLUIDO_LUBRIFICANTE', 'Fluidos lubrificantes e hidráulicos'), ('INSPECAO_GENERICA', 'Inspeção genérica (sem medições específicas)'), ('ALINHAMENTO_EIXOS', 'Alinhamento a laser entre eixos (não implementado)'), ('ALINHAMENTO_POLIAS', 'Alinhamento a laser entre polias (não implementado)'), ('TERMOGRAFIA_MECANICA', 'Termografia — sistemas mecânicos (não implementado)'), ('ENSAIO_ELETRICO_TC', 'Ensaios elétricos — TC (não implementado)'), ('ENSAIO_ELETRICO_TP', 'Ensaios elétricos — TP (não implementado)'), ('ENSAIO_ELETRICO_DJ', 'Ensaios elétricos — disjuntor (não implementado)'), ('ENSAIO_ELETRICO_CS', 'Ensaios elétricos — chave seccionadora (não implementado)'), ('ENSAIO_ELETRICO_RP', 'Ensaios elétricos — relé de proteção (não implementado)')], default='', help_text='Medições, imagens e norma que o relatório técnico desta tecnologia mostra. Vazio = não configurado: o relatório não é gerado até a escolha.', max_length=20, verbose_name='Módulo técnico do relatório'),
        ),
    ]
