# Generated by Django 5.1.4 on 2026-10-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0031_dados_modulo_das_tecnologias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterioseveridadevibracao',
            name='classe',
            field=models.CharField(choices=[('I', 'Classe I (até 15 kW)'), ('G2', 'Grupo 2 (15 a 300 kW) — ISO 20816-3'), ('G1', 'Grupo 1 (acima de 300 kW) — ISO 20816-3'), ('II', 'Classe II (15–75 kW) — ISO 10816-1, histórico'), ('III', 'Classe III (base rígida) — ISO 10816-1, histórico'), ('IV', 'Classe IV (base flexível) — ISO 10816-1, histórico')], max_length=3, verbose_name='Grupo/classe da máquina'),
        ),
        migrations.AlterField(
            model_name='criterioseveridadevibracao',
            name='origem',
            field=models.CharField(choices=[('NORMA', 'Norma (valor publicado)'), ('RESPONSAVEL_TECNICO', 'Critério do responsável técnico'), ('ACORDO_CLIENTE', 'Acordo com o cliente / contrato'), ('LEGADO', 'Legado (origem não documentada)')], default='NORMA', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='classe_iso',
            field=models.CharField(blank=True, choices=[('I', 'Classe I (até 15 kW)'), ('G2', 'Grupo 2 (15 a 300 kW) — ISO 20816-3'), ('G1', 'Grupo 1 (acima de 300 kW) — ISO 20816-3'), ('II', 'Classe II (15–75 kW) — ISO 10816-1, histórico'), ('III', 'Classe III (base rígida) — ISO 10816-1, histórico'), ('IV', 'Classe IV (base flexível) — ISO 10816-1, histórico')], default='', help_text='Grupo da máquina no critério de severidade de vibração. Vazio quando o tipo do equipamento não é avaliado por vibração.', max_length=3, verbose_name='Classe ISO (vibração)'),
        ),
    ]
