# Generated by Django 5.1.4 on 2026-10-08 05:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0033_criterios_iso_20816'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterioseveridadevibracao',
            name='desloc_ab',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Deslocamento A/B (µm RMS)'),
        ),
        migrations.AddField(
            model_name='criterioseveridadevibracao',
            name='desloc_bc',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Deslocamento B/C (µm RMS)'),
        ),
        migrations.AddField(
            model_name='criterioseveridadevibracao',
            name='desloc_cd',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Deslocamento C/D (µm RMS)'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo_base',
            field=models.CharField(blank=True, choices=[('RIGIDA', 'Rígida'), ('FLEXIVEL', 'Flexível')], help_text='Rígida ou flexível — nos Grupos 1 e 2 decide a coluna de limites da ISO 20816-3.', max_length=10, verbose_name='Tipo de base (fundação)'),
        ),
        migrations.AlterField(
            model_name='dadostecnicosmotor',
            name='tipo_base',
            field=models.CharField(blank=True, choices=[('RIGIDA', 'Rígida'), ('FLEXIVEL', 'Flexível')], help_text='Rígida ou flexível — decide a coluna de limites da ISO 20816-3 (Grupos 1 e 2).', max_length=10, verbose_name='Tipo de base'),
        ),
    ]
