# Generated by Django 5.1.4 on 2026-06-22 22:26

import apps.accounts.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome completo')),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador'), ('GESTOR', 'Gestor/Supervisor'), ('TECNICO', 'Técnico/Analista'), ('CLIENTE_CORP', 'Cliente — Gestor Corporativo'), ('CLIENTE_LOCAL', 'Cliente — Gestor Local'), ('CLIENTE_PCM', 'Cliente — PCM'), ('CLIENTE_MANUT', 'Cliente — Manutentor')], default='TECNICO', max_length=20, verbose_name='Perfil de acesso')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('cargo', models.CharField(blank=True, max_length=80, verbose_name='Cargo/Função')),
                ('conselho_classe', models.CharField(blank=True, help_text='Ex.: CREA — necessário para assinar laudos.', max_length=60, verbose_name='Conselho de Classe')),
                ('assinatura_digital', models.ImageField(blank=True, null=True, upload_to='assinaturas/', verbose_name='Assinatura digital')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso ao admin')),
                ('cliente', models.ForeignKey(blank=True, help_text='Preenchido para perfis do tipo Cliente (Portal do Cliente).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='cadastros.cliente', verbose_name='Cliente vinculado')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='cadastros.empresa', verbose_name='Empresa contratada')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
