# Generated by Django 5.1.4 on 2026-07-22 23:48

from django.db import migrations, models

#: Nível equivalente ao perfil que o usuário já tinha, para ninguém perder acesso
#: no deploy: Administrador vira Master (continua curando os dados de sistema).
NIVEL_POR_PERFIL = {
    "ADMIN": "MASTER",
    "GESTOR": "SENIOR",
    "TECNICO": "PLENO",
    "CLIENTE_CORP": "SENIOR",
    "CLIENTE_LOCAL": "PLENO",
    "CLIENTE_PCM": "PLENO",
    "CLIENTE_MANUT": "JUNIOR",
}


def definir_nivel_pelos_perfis(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for perfil, nivel in NIVEL_POR_PERFIL.items():
        User.objects.filter(perfil=perfil).update(nivel=nivel)


def reverter(apps, schema_editor):
    """Sem volta necessária: o campo inteiro é removido ao desfazer."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nivel',
            field=models.CharField(choices=[('MASTER', 'Master'), ('SENIOR', 'Sênior'), ('PLENO', 'Pleno'), ('JUNIOR', 'Júnior')], default='PLENO', help_text='Master cura os dados de sistema e concede acessos; Júnior/Pleno não excluem.', max_length=10, verbose_name='Nível de acesso'),
        ),
        migrations.RunPython(definir_nivel_pelos_perfis, reverter),
    ]
