# Generated by Django 5.1.4 on 2026-09-09 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0021_seed_definicao_vibracao'),
        ('coletas', '0009_relatorio_numero_hifen'),
        ('osp', '0008_ordemservico_resultado_confirmacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceamentoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero', models.PositiveSmallIntegerField(help_text='1 ou 2', verbose_name='Plano nº')),
                ('descricao', models.CharField(blank=True, help_text='Ex.: lado acoplamento', max_length=120, verbose_name='Descrição')),
                ('massa_teste_g', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Massa de teste (g)')),
                ('angulo_teste', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Ângulo da massa de teste (°)')),
                ('massa_final_g', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Massa final (g)')),
                ('angulo_final', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Ângulo da massa final (°)')),
            ],
            options={
                'verbose_name': 'Plano de balanceamento',
                'verbose_name_plural': 'Planos de balanceamento',
                'ordering': ['numero'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('BALANCEAMENTO', 'Balanceamento dinâmico em campo'), ('ALINHAMENTO', 'Alinhamento a laser')], max_length=15, verbose_name='Tipo de serviço')),
                ('data_execucao', models.DateField(verbose_name='Data de execução')),
                ('rotacao_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Rotação (Hz)')),
                ('rotacao_rpm', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Rotação (RPM)')),
                ('custo_servico', models.DecimalField(blank=True, decimal_places=2, help_text='Informado a cada serviço — não vem de tabela de preço.', max_digits=12, null=True, verbose_name='Custo do serviço (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('achado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='coletas.achado', verbose_name='Análise de origem')),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to=settings.AUTH_USER_MODEL, verbose_name='Analista responsável')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='cadastros.cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='cadastros.equipamento')),
                ('instrumento', models.ForeignKey(blank=True, help_text='Rastreabilidade de calibração (item 3.1.10).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='cadastros.instrumento')),
                ('osp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='osp.ordemservico', verbose_name='OSP de origem')),
                ('relatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos', to='coletas.relatorio', verbose_name='Relatório em que sai')),
            ],
            options={
                'verbose_name': 'Serviço de campo',
                'verbose_name_plural': 'Serviços de campo',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EconomiaEnergetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tensao_v', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Tensão do motor (V)')),
                ('corrente_antes_a', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Corrente antes (A)')),
                ('corrente_apos_a', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Corrente após (A)')),
                ('fator_potencia', models.DecimalField(decimal_places=3, help_text='Medido no motor.', max_digits=4, verbose_name='Fator de potência')),
                ('horas_dia', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Regime diário de operação (h)')),
                ('dias_ano', models.PositiveSmallIntegerField(help_text='Na planilha era fixo em 365.', verbose_name='Dias de operação por ano')),
                ('custo_kwh', models.DecimalField(decimal_places=4, help_text='Tarifa vigente informada pelo cliente.', max_digits=8, verbose_name='Custo da energia (R$/kWh)')),
                ('reducao_kw', models.DecimalField(decimal_places=4, editable=False, max_digits=12, null=True, verbose_name='Redução de demanda (kW)')),
                ('economia_kwh_ano', models.DecimalField(decimal_places=2, editable=False, max_digits=14, null=True, verbose_name='Economia (kWh/ano)')),
                ('economia_rs_ano', models.DecimalField(decimal_places=2, editable=False, max_digits=14, null=True, verbose_name='Economia (R$/ano)')),
                ('payback_meses', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8, null=True, verbose_name='Payback (meses)')),
                ('payback_dias', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=8, null=True, verbose_name='Payback (dias)')),
                ('retorno_ano', models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='O "4,67" da planilha: quantas vezes o serviço se paga no ano.', max_digits=10, null=True, verbose_name='Retorno (×/ano)')),
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='economia', to='servicos.servicocampo')),
            ],
            options={
                'verbose_name': 'Economia energética',
                'verbose_name_plural': 'Economias energéticas',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceamentoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('numero_mancal', models.PositiveSmallIntegerField(verbose_name='Mancal')),
                ('direcao', models.CharField(choices=[('H', 'Horizontal'), ('V', 'Vertical'), ('A', 'Axial')], max_length=1, verbose_name='Direção')),
                ('reference_mms', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Reference run (mm/s)')),
                ('reference_fase', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Reference run — fase (°)')),
                ('trial_mms', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Trial run (mm/s)')),
                ('trial_fase', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Trial run — fase (°)')),
                ('trim_mms', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Trim run (mm/s)')),
                ('trim_fase', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Trim run — fase (°)')),
                ('residual_pct', models.DecimalField(decimal_places=3, editable=False, max_digits=8, null=True, verbose_name='Vibração residual (%)')),
                ('reducao_pct', models.DecimalField(decimal_places=3, editable=False, max_digits=8, null=True, verbose_name='Redução obtida (%)')),
                ('zona_iso', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Zona ISO do resultado')),
                ('criticidade', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico')], editable=False, max_length=8, verbose_name='Criticidade final')),
                ('eficaz', models.BooleanField(default=False, editable=False, verbose_name='Balanceamento eficaz')),
                ('diagnostico', models.TextField(blank=True, editable=False, verbose_name='Diagnóstico')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontos', to='servicos.balanceamentoplano', verbose_name='Plano corrigido por este ponto')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='servicos.servicocampo')),
            ],
            options={
                'verbose_name': 'Ponto de balanceamento',
                'verbose_name_plural': 'Pontos de balanceamento',
                'ordering': ['numero_mancal', 'direcao'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='balanceamentoplano',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='servicos.servicocampo'),
        ),
        migrations.AddConstraint(
            model_name='balanceamentoplano',
            constraint=models.UniqueConstraint(fields=('servico', 'numero'), name='uniq_plano_por_servico'),
        ),
    ]
