# Generated by Django 5.1.4 on 2026-09-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceamentoponto',
            name='trim_fase',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Trim run — fase (°)'),
        ),
        migrations.AlterField(
            model_name='balanceamentoponto',
            name='trim_mms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Trim run (mm/s)'),
        ),
    ]
