# Generated by Django 5.1.4 on 2026-09-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_balanceamentoponto_trim_fase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicocampo',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Manutenção corretiva', 'verbose_name_plural': 'Manutenções corretivas'},
        ),
    ]
