# Generated by Django 5.1.4 on 2026-09-10 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0010_carregamento_tipo_corretiva'),
        ('servicos', '0003_manutencao_corretiva_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicocampo',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servico_corretivo', to='coletas.iteminspecao'),
        ),
    ]
