# Generated by Django 5.1.4 on 2026-09-10 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletas', '0010_carregamento_tipo_corretiva'),
        ('servicos', '0004_servicocampo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicocampo',
            name='analise_tecnica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balanceamento_tecnico', to='coletas.achado', verbose_name='Análise técnica da intervenção'),
        ),
    ]
