# Generated by Django 5.1.4 on 2026-09-10 07:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_servicocampo_analise_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceamentoponto',
            name='identificacao',
            field=models.CharField(blank=True, help_text="Ex.: 'Motor — lado livre' (útil quando há mais de um mancal por eixo).", max_length=120, verbose_name='Identificação'),
        ),
        migrations.AddField(
            model_name='servicocampo',
            name='ponto_foco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='servicos.balanceamentoponto', verbose_name='Ponto de foco do balanceamento'),
        ),
        migrations.AlterField(
            model_name='balanceamentoplano',
            name='numero',
            field=models.PositiveSmallIntegerField(help_text='1 ou 2', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Plano nº'),
        ),
        migrations.AddConstraint(
            model_name='balanceamentoplano',
            constraint=models.CheckConstraint(condition=models.Q(('numero__gte', 1), ('numero__lte', 2)), name='plano_numero_1_ou_2'),
        ),
    ]
