# Generated by Django 5.1.4 on 2026-09-10 11:05

import django.core.validators
from django.db import migrations, models


def preencher_investimento_existente(apps, schema_editor):
    """
    Backfill: registros de EconomiaEnergetica criados antes deste campo existir tinham
    o "investimento" lido de ServicoCampo.custo_servico (campo sem tela própria). Copia
    o que já existir para o novo campo e recalcula os derivados com a mesma regra pura
    (rules.calcular_economia, independente do estado congelado da migração). Sem dado
    histórico para copiar, fica nulo — não inventa valor.
    """
    from apps.servicos import rules

    EconomiaEnergetica = apps.get_model("servicos", "EconomiaEnergetica")
    for economia in EconomiaEnergetica.objects.filter(investimento__isnull=True).select_related("servico"):
        custo = economia.servico.custo_servico
        if custo is None:
            continue
        resultado = rules.calcular_economia(
            tensao_v=economia.tensao_v,
            corrente_antes_a=economia.corrente_antes_a,
            corrente_apos_a=economia.corrente_apos_a,
            fator_potencia=economia.fator_potencia,
            horas_dia=economia.horas_dia,
            dias_ano=economia.dias_ano,
            custo_kwh=economia.custo_kwh,
            investimento=custo,
        )
        economia.investimento = custo
        economia.reducao_corrente_a = resultado.reducao_corrente_a
        economia.reducao_kw = resultado.reducao_kw
        economia.economia_kwh_ano = resultado.economia_kwh_ano
        economia.economia_rs_ano = resultado.economia_rs_ano
        economia.payback_meses = resultado.payback_meses
        economia.payback_dias = resultado.payback_dias
        economia.retorno_ano = resultado.retorno_ano
        economia.save()


def reverter_backfill(apps, schema_editor):
    # Nada a desfazer: reverter só descarta o preenchimento do campo novo — o dado
    # original (ServicoCampo.custo_servico) nunca é tocado por este backfill.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_balanceamentoponto_identificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='economiaenergetica',
            name='investimento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custo do serviço executado — numerador do Payback. Obrigatório na API (exigido pelo serializer); nulo no banco só para registros anteriores a este campo existir.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Investimento realizado (R$)'),
        ),
        migrations.AddField(
            model_name='economiaenergetica',
            name='reducao_corrente_a',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=9, null=True, verbose_name='Redução de corrente (A)'),
        ),
        migrations.AlterField(
            model_name='economiaenergetica',
            name='corrente_antes_a',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Corrente antes (A)'),
        ),
        migrations.AlterField(
            model_name='economiaenergetica',
            name='corrente_apos_a',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Corrente após (A)'),
        ),
        migrations.AlterField(
            model_name='economiaenergetica',
            name='custo_kwh',
            field=models.DecimalField(decimal_places=4, help_text='Tarifa vigente informada pelo cliente.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo da energia (R$/kWh)'),
        ),
        migrations.AlterField(
            model_name='economiaenergetica',
            name='dias_ano',
            field=models.PositiveSmallIntegerField(help_text='Na planilha era fixo em 365.', validators=[django.core.validators.MaxValueValidator(366)], verbose_name='Dias de operação por ano'),
        ),
        migrations.AlterField(
            model_name='economiaenergetica',
            name='fator_potencia',
            field=models.DecimalField(decimal_places=3, help_text='Medido no motor.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Fator de potência'),
        ),
        migrations.AlterField(
            model_name='economiaenergetica',
            name='horas_dia',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Regime diário de operação (h)'),
        ),
        migrations.AlterField(
            model_name='economiaenergetica',
            name='tensao_v',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tensão do motor (V)'),
        ),
        migrations.RunPython(preencher_investimento_existente, reverter_backfill),
    ]
