# Generated by Django 5.1.4 on 2026-09-24 23:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0027_dadostecnicostransformador_possui_tanque_expansao_and_more'),
        ('coletas', '0010_carregamento_tipo_corretiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ensaio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('modulo', models.CharField(choices=[('VIBRACAO', 'Vibração'), ('TERMOGRAFIA', 'Termografia'), ('OLEO_ISOLANTE', 'Óleo isolante (transformador)'), ('ENSAIO_ELETRICO', 'Ensaios elétricos (transformador)')], max_length=20, verbose_name='Módulo do relatório')),
                ('titulo_ficha', models.CharField(max_length=120, verbose_name='Título da ficha')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('rotulo_conclusao', models.CharField(default='Conclusão', max_length=40, verbose_name='Rótulo da conclusão')),
                ('rotulo_informacoes', models.CharField(default='Informações Adicionais', max_length=40, verbose_name='Rótulo das informações')),
                ('rotulo_proxima', models.CharField(default='Data da Próxima Coleta', max_length=40, verbose_name='Rótulo da próxima data')),
                ('nota_tecnica', models.TextField(blank=True, help_text='Notas fixas impressas na ficha (norma, limites de quantificação…). Uma por linha.', verbose_name='Nota técnica')),
            ],
            options={
                'verbose_name': 'Ensaio',
                'verbose_name_plural': 'Ensaios',
                'ordering': ['modulo', 'ordem'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemChecklistVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('grupo', models.CharField(choices=[('GERAL', 'Geral'), ('TANQUE_EXPANSAO', 'Exclusivo para equipamentos com tanque de expansão')], default='GERAL', max_length=20, verbose_name='Grupo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Item de inspeção visual',
                'verbose_name_plural': 'Itens de inspeção visual',
                'ordering': ['grupo', 'ordem', 'nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Ponto de coleta',
                'verbose_name_plural': 'Pontos de coleta',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoFluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de fluido isolante',
                'verbose_name_plural': 'Tipos de fluido isolante',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColetaOleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_coleta', models.DateField(verbose_name='Data da coleta')),
                ('amostrador', models.CharField(blank=True, max_length=120, verbose_name='Amostrador')),
                ('temperatura_amostra_c', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Temperatura da amostra (°C)')),
                ('temperatura_ambiente_c', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Temperatura ambiente (°C)')),
                ('umidade_relativa_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Umidade relativa do ar (%)')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coleta_oleo', to='coletas.iteminspecao')),
                ('ensaios', models.ManyToManyField(blank=True, related_name='+', to='ensaios.ensaio', verbose_name='Ensaios solicitados')),
                ('ponto_coleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ensaios.pontocoleta')),
                ('tipo_fluido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ensaios.tipofluido')),
            ],
            options={
                'verbose_name': 'Coleta de amostra de óleo',
                'verbose_name_plural': 'Coletas de amostra de óleo',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParametroEnsaio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo', models.CharField(help_text='Identificador estável (ex.: H2, VISCOSIDADE).', max_length=30, verbose_name='Código')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('unidade', models.CharField(blank=True, max_length=20, verbose_name='Unidade')),
                ('norma', models.CharField(blank=True, max_length=80, verbose_name='Norma')),
                ('tipo_limite', models.CharField(choices=[('MAXIMO', 'Máximo'), ('MINIMO', 'Mínimo'), ('FAIXA', 'Faixa'), ('QUALITATIVO', 'Qualitativo'), ('INFORMATIVO', 'Informativo (sem limite)')], default='INFORMATIVO', max_length=12, verbose_name='Tipo de limite')),
                ('limite', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Limite (máx., mín. ou início da faixa)')),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Fim da faixa')),
                ('referencia_texto', models.CharField(blank=True, max_length=40, verbose_name='Referência qualitativa')),
                ('casas_decimais', models.PositiveSmallIntegerField(default=2, verbose_name='Casas decimais')),
                ('calculado', models.BooleanField(default=False, help_text='Calculado pelo sistema a partir de outros valores do ensaio; não é digitado.', verbose_name='Calculado')),
                ('no_grafico', models.BooleanField(default=True, verbose_name='Entra no gráfico')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('ensaio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='ensaios.ensaio')),
            ],
            options={
                'verbose_name': 'Parâmetro de ensaio',
                'verbose_name_plural': 'Parâmetros de ensaio',
                'ordering': ['ensaio', 'ordem'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroEnsaioEletrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_ensaio', models.DateField(verbose_name='Data do ensaio')),
                ('analista', models.CharField(blank=True, max_length=120, verbose_name='Analista')),
                ('tap', models.CharField(blank=True, max_length=10, verbose_name='TAP')),
                ('tensao_tap_v', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Tensão do TAP (V)')),
                ('temperatura_oleo_c', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Temperatura do óleo (°C)')),
                ('temperatura_ambiente_c', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Temperatura ambiente (°C)')),
                ('umidade_relativa_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Umidade relativa (%)')),
                ('ensaios', models.ManyToManyField(blank=True, related_name='+', to='ensaios.ensaio', verbose_name='Ensaios solicitados')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_eletrico', to='coletas.iteminspecao')),
            ],
            options={
                'verbose_name': 'Registro de ensaios elétricos',
                'verbose_name_plural': 'Registros de ensaios elétricos',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultadoEnsaio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('situacao', models.CharField(choices=[('REALIZADO', 'Realizado'), ('NAO_COLETADO', 'Amostra não coletada'), ('NAO_REALIZADO', 'Não realizado'), ('SEM_RESULTADO', 'Aguardando resultado')], default='SEM_RESULTADO', max_length=15, verbose_name='Situação')),
                ('numero_laudo', models.CharField(blank=True, max_length=40, verbose_name='Número do laudo')),
                ('criticidade', models.CharField(blank=True, choices=[('ROTINA', 'Rotina'), ('ALERTA', 'Alerta'), ('CRITICA', 'Crítica')], max_length=10, verbose_name='Criticidade')),
                ('data_analise', models.DateField(blank=True, null=True, verbose_name='Data da análise')),
                ('data_proxima', models.DateField(blank=True, null=True, verbose_name='Data da próxima coleta/análise')),
                ('conclusao', models.TextField(blank=True, verbose_name='Conclusão / observações')),
                ('recomendacao', models.TextField(blank=True, verbose_name='Recomendação')),
                ('informacoes_adicionais', models.TextField(blank=True, verbose_name='Informações adicionais')),
                ('origem', models.CharField(choices=[('MANUAL', 'Digitado'), ('PLANILHA', 'Planilha'), ('API', 'Integração (API)'), ('ARQUIVO', 'Arquivo do laboratório')], default='MANUAL', max_length=10, verbose_name='Origem do dado')),
                ('ensaio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='ensaios.ensaio')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_ensaio', to='cadastros.instrumento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_ensaio', to='coletas.iteminspecao')),
            ],
            options={
                'verbose_name': 'Resultado de ensaio',
                'verbose_name_plural': 'Resultados de ensaio',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValorParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('serie', models.CharField(blank=True, help_text='Fase (R×T), ligação (R×I) ou par de terminais.', max_length=40, verbose_name='Série')),
                ('posicao', models.DecimalField(blank=True, decimal_places=2, help_text='Tempo em segundos na R×I.', max_digits=10, null=True, verbose_name='Posição')),
                ('valor', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Valor')),
                ('valor_texto', models.CharField(blank=True, max_length=60, verbose_name='Valor como recebido / qualitativo')),
                ('estado', models.CharField(choices=[('MEDIDO', 'Medido'), ('ABAIXO_LD', 'Abaixo do limite de detecção'), ('ABAIXO_LQ', 'Abaixo do limite de quantificação'), ('NAO_DETECTADO', 'Não detectado'), ('ACIMA_ESCALA', 'Acima do fundo de escala'), ('INDISPONIVEL', 'Indisponível')], default='MEDIDO', max_length=15, verbose_name='Estado')),
                ('limite_deteccao', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Limite de detecção')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='ensaios.parametroensaio')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='ensaios.resultadoensaio')),
            ],
            options={
                'verbose_name': 'Valor de parâmetro',
                'verbose_name_plural': 'Valores de parâmetros',
                'ordering': ['parametro__ordem', 'serie', 'posicao'],
            },
        ),
        migrations.CreateModel(
            name='InspecaoVisualColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('estado', models.CharField(choices=[('OK', 'Condição Normal'), ('NC', 'Não Conformidade'), ('NA', 'Não Aplicável')], max_length=2, verbose_name='Estado')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ensaios/inspecao_visual/', verbose_name='Foto')),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecao_visual', to='ensaios.coletaoleo')),
                ('item_checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ensaios.itemchecklistvisual')),
            ],
            options={
                'verbose_name': 'Item da inspeção visual',
                'verbose_name_plural': 'Inspeção visual',
                'ordering': ['item_checklist__grupo', 'item_checklist__ordem'],
                'constraints': [models.UniqueConstraint(fields=('coleta', 'item_checklist'), name='uniq_inspecao_visual_item')],
            },
        ),
        migrations.AddConstraint(
            model_name='parametroensaio',
            constraint=models.UniqueConstraint(fields=('ensaio', 'codigo'), name='uniq_parametro_ensaio_codigo'),
        ),
        migrations.AddConstraint(
            model_name='resultadoensaio',
            constraint=models.UniqueConstraint(fields=('item', 'ensaio'), name='uniq_resultado_item_ensaio'),
        ),
    ]
