# Generated by Django 5.1.4 on 2026-10-01 04:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0031_dados_modulo_das_tecnologias'),
        ('coletas', '0010_carregamento_tipo_corretiva'),
        ('ensaios', '0002_catalogos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColetaFluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('aplicacao', models.CharField(choices=[('LUBRIFICANTE', 'Lubrificante'), ('HIDRAULICO', 'Hidráulico')], max_length=15, verbose_name='Aplicação do fluido')),
                ('fluido_informado', models.CharField(blank=True, max_length=120, verbose_name='Fluido (quando não cadastrado)')),
                ('grau_viscosidade', models.CharField(blank=True, max_length=20, verbose_name='Grau de viscosidade')),
                ('identificacao_amostra', models.CharField(blank=True, help_text='Etiqueta/número da amostra no laboratório.', max_length=40, verbose_name='Identificação da amostra')),
                ('data_coleta', models.DateField(verbose_name='Data da coleta')),
                ('amostrador', models.CharField(blank=True, max_length=120, verbose_name='Amostrador')),
                ('temperatura_fluido_c', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Temperatura do fluido (°C)')),
                ('temperatura_ambiente_c', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Temperatura ambiente (°C)')),
                ('condicao_operacional', models.CharField(blank=True, choices=[('EM_OPERACAO', 'Em operação'), ('APOS_PARADA', 'Logo após a parada'), ('PARADO', 'Parado')], max_length=15, verbose_name='Condição operacional na coleta')),
                ('horas_equipamento', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Horas do equipamento')),
                ('horas_fluido', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Horas do fluido (desde a última troca)')),
                ('data_ultima_troca', models.DateField(blank=True, null=True, verbose_name='Data da última troca do fluido')),
                ('complemento_recente', models.BooleanField(blank=True, null=True, verbose_name='Complemento recente de fluido')),
                ('volume_complemento_l', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Volume complementado (L)')),
                ('troca_filtro_recente', models.BooleanField(blank=True, null=True, verbose_name='Troca recente de filtro')),
                ('intervencao_recente', models.TextField(blank=True, verbose_name='Intervenção/manutenção recente')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Coleta de amostra de fluido',
                'verbose_name_plural': 'Coletas de amostra de fluido',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoFluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('fabricante', models.CharField(blank=True, max_length=80, verbose_name='Fabricante')),
                ('aplicacao', models.CharField(blank=True, choices=[('LUBRIFICANTE', 'Lubrificante'), ('HIDRAULICO', 'Hidráulico')], max_length=15, verbose_name='Aplicação')),
                ('grau_viscosidade', models.CharField(blank=True, help_text='Ex.: ISO VG 46', max_length=20, verbose_name='Grau de viscosidade')),
                ('viscosidade_40c_cst', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Viscosidade a 40 °C do óleo novo (cSt)')),
                ('viscosidade_100c_cst', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Viscosidade a 100 °C do óleo novo (cSt)')),
                ('indice_viscosidade', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Índice de viscosidade')),
            ],
            options={
                'verbose_name': 'Produto lubrificante / hidráulico',
                'verbose_name_plural': 'Produtos lubrificantes / hidráulicos',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenciaParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('aplicacao', models.CharField(blank=True, choices=[('LUBRIFICANTE', 'Lubrificante'), ('HIDRAULICO', 'Hidráulico')], max_length=15, verbose_name='Aplicação')),
                ('tipo', models.CharField(choices=[('MAXIMO', 'Máximo (alerta/crítico acima do limite)'), ('MINIMO', 'Mínimo (alerta/crítico abaixo do limite)'), ('VARIACAO', 'Variação em relação ao valor de base (%)'), ('CODIGO_ISO', 'Meta de limpeza ISO 4406'), ('QUALITATIVO', 'Resultado esperado (texto)')], max_length=12, verbose_name='Tipo')),
                ('valor_base', models.DecimalField(blank=True, decimal_places=4, help_text='Óleo novo/nominal, para referência do tipo Variação.', max_digits=14, null=True, verbose_name='Valor de base')),
                ('limite_alerta', models.DecimalField(blank=True, decimal_places=4, help_text='Na Variação, em %; na meta ISO, graus de código acima da meta.', max_digits=14, null=True, verbose_name='Limite de alerta')),
                ('limite_critico', models.DecimalField(blank=True, decimal_places=4, help_text='Na Variação, em %; na meta ISO, graus de código acima da meta.', max_digits=14, null=True, verbose_name='Limite crítico')),
                ('referencia_texto', models.CharField(blank=True, help_text='Meta ISO 4406 (ex.: 17/15/12) ou resultado esperado (ex.: Límpido).', max_length=40, verbose_name='Meta / resultado esperado')),
                ('origem', models.CharField(choices=[('NORMA', 'Norma'), ('FABRICANTE_EQUIPAMENTO', 'Fabricante do equipamento'), ('FABRICANTE_FLUIDO', 'Fabricante do fluido'), ('LABORATORIO', 'Laboratório'), ('CLIENTE', 'Acordo com o cliente / contrato'), ('OLEO_NOVO', 'Óleo novo (baseline medido)')], max_length=25, verbose_name='Origem')),
                ('fonte', models.CharField(blank=True, help_text='Norma, manual do fabricante, laudo, contrato ou acordo que sustenta o valor.', max_length=250, verbose_name='Fonte')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Vigência — início')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='Vigência — fim')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Referência de parâmetro (fluidos)',
                'verbose_name_plural': 'Referências de parâmetros (fluidos)',
                'ordering': ['parametro__ensaio', 'parametro__ordem', '-vigencia_inicio'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoPadraoEnsaio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('aplicacao', models.CharField(choices=[('LUBRIFICANTE', 'Lubrificante'), ('HIDRAULICO', 'Hidráulico')], max_length=15, verbose_name='Aplicação')),
            ],
            options={
                'verbose_name': 'Ensaio solicitado por padrão',
                'verbose_name_plural': 'Ensaios solicitados por padrão',
                'ordering': ['-criado_em'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='parametroensaio',
            name='grupo',
            field=models.CharField(blank=True, help_text='Agrupa as linhas da ficha (ex.: Metais de desgaste, Contaminantes, Aditivos).', max_length=40, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='parametroensaio',
            name='simbolo',
            field=models.CharField(blank=True, help_text='Ex.: Fe, Cu, Si.', max_length=10, verbose_name='Símbolo'),
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='modulo',
            field=models.CharField(blank=True, choices=[('VIBRACAO', 'Vibração'), ('BALANCEAMENTO', 'Balanceamento dinâmico (corretiva)'), ('TERMOGRAFIA', 'Termografia'), ('OLEO_ISOLANTE', 'Óleo isolante (transformador)'), ('ENSAIO_ELETRICO', 'Ensaios elétricos — transformador (TRF)'), ('FLUIDO_LUBRIFICANTE', 'Fluidos lubrificantes e hidráulicos'), ('INSPECAO_GENERICA', 'Inspeção genérica (sem medições específicas)'), ('ALINHAMENTO_EIXOS', 'Alinhamento a laser entre eixos (não implementado)'), ('ALINHAMENTO_POLIAS', 'Alinhamento a laser entre polias (não implementado)'), ('TERMOGRAFIA_MECANICA', 'Termografia — sistemas mecânicos (não implementado)'), ('ENSAIO_ELETRICO_TC', 'Ensaios elétricos — TC (não implementado)'), ('ENSAIO_ELETRICO_TP', 'Ensaios elétricos — TP (não implementado)'), ('ENSAIO_ELETRICO_DJ', 'Ensaios elétricos — disjuntor (não implementado)'), ('ENSAIO_ELETRICO_CS', 'Ensaios elétricos — chave seccionadora (não implementado)'), ('ENSAIO_ELETRICO_RP', 'Ensaios elétricos — relé de proteção (não implementado)')], help_text='Em qual coleta o ponto aparece (óleo isolante, fluidos…). Vazio = em todas.', max_length=20, verbose_name='Tecnologia'),
        ),
        migrations.AddField(
            model_name='resultadoensaio',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=120, verbose_name='Laboratório'),
        ),
        migrations.AddField(
            model_name='valorparametro',
            name='metodo',
            field=models.CharField(blank=True, help_text='Só quando difere da norma do catálogo (ex.: ASTM D4951 no lugar de D5185).', max_length=60, verbose_name='Método/norma do laboratório'),
        ),
        migrations.AlterField(
            model_name='ensaio',
            name='modulo',
            field=models.CharField(choices=[('VIBRACAO', 'Vibração'), ('BALANCEAMENTO', 'Balanceamento dinâmico (corretiva)'), ('TERMOGRAFIA', 'Termografia'), ('OLEO_ISOLANTE', 'Óleo isolante (transformador)'), ('ENSAIO_ELETRICO', 'Ensaios elétricos — transformador (TRF)'), ('FLUIDO_LUBRIFICANTE', 'Fluidos lubrificantes e hidráulicos'), ('INSPECAO_GENERICA', 'Inspeção genérica (sem medições específicas)'), ('ALINHAMENTO_EIXOS', 'Alinhamento a laser entre eixos (não implementado)'), ('ALINHAMENTO_POLIAS', 'Alinhamento a laser entre polias (não implementado)'), ('TERMOGRAFIA_MECANICA', 'Termografia — sistemas mecânicos (não implementado)'), ('ENSAIO_ELETRICO_TC', 'Ensaios elétricos — TC (não implementado)'), ('ENSAIO_ELETRICO_TP', 'Ensaios elétricos — TP (não implementado)'), ('ENSAIO_ELETRICO_DJ', 'Ensaios elétricos — disjuntor (não implementado)'), ('ENSAIO_ELETRICO_CS', 'Ensaios elétricos — chave seccionadora (não implementado)'), ('ENSAIO_ELETRICO_RP', 'Ensaios elétricos — relé de proteção (não implementado)')], max_length=20, verbose_name='Módulo do relatório'),
        ),
        migrations.AlterField(
            model_name='ensaio',
            name='sigla',
            field=models.CharField(max_length=10, verbose_name='Sigla'),
        ),
        migrations.AddConstraint(
            model_name='ensaio',
            constraint=models.UniqueConstraint(fields=('modulo', 'sigla'), name='uniq_ensaio_modulo_sigla'),
        ),
        migrations.AddField(
            model_name='coletafluido',
            name='ensaios',
            field=models.ManyToManyField(blank=True, related_name='+', to='ensaios.ensaio', verbose_name='Ensaios solicitados'),
        ),
        migrations.AddField(
            model_name='coletafluido',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coleta_fluido', to='coletas.iteminspecao'),
        ),
        migrations.AddField(
            model_name='coletafluido',
            name='ponto_coleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ensaios.pontocoleta'),
        ),
        migrations.AddField(
            model_name='coletafluido',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas', to='ensaios.produtofluido'),
        ),
        migrations.AddField(
            model_name='referenciaparametro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencias_fluido', to='cadastros.cliente'),
        ),
        migrations.AddField(
            model_name='referenciaparametro',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencias_fluido', to='cadastros.equipamento'),
        ),
        migrations.AddField(
            model_name='referenciaparametro',
            name='parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='ensaios.parametroensaio'),
        ),
        migrations.AddField(
            model_name='referenciaparametro',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='ensaios.produtofluido'),
        ),
        migrations.AddField(
            model_name='solicitacaopadraoensaio',
            name='ensaio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_padrao', to='ensaios.ensaio'),
        ),
        migrations.AddConstraint(
            model_name='solicitacaopadraoensaio',
            constraint=models.UniqueConstraint(fields=('aplicacao', 'ensaio'), name='uniq_solicitacao_padrao'),
        ),
    ]
