# Generated by Django 5.1.4 on 2026-10-03 19:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensaios', '0005_normas_fluidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='coletafluido',
            name='volume_reservatorio_l',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Volume do reservatório (L)'),
        ),
    ]
