# Generated by Django 5.1.4 on 2026-10-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensaios', '0007_fluidos_modelo_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciaparametro',
            name='base_grau_iso',
            field=models.BooleanField(default=False, help_text='Na Variação da viscosidade a 40 °C: a base é o grau ISO VG do fluido da coleta (ISO VG 68 → 68 cSt), em vez de um valor fixo.', verbose_name='Base = grau ISO VG do fluido da amostra'),
        ),
        migrations.AlterField(
            model_name='referenciaparametro',
            name='origem',
            field=models.CharField(choices=[('NORMA', 'Norma'), ('FABRICANTE_EQUIPAMENTO', 'Fabricante do equipamento'), ('FABRICANTE_FLUIDO', 'Fabricante do fluido'), ('LABORATORIO', 'Laboratório'), ('CLIENTE', 'Acordo com o cliente / contrato'), ('OLEO_NOVO', 'Óleo novo (baseline medido)'), ('RESPONSAVEL_TECNICO', 'Critério do responsável técnico')], max_length=25, verbose_name='Origem'),
        ),
    ]
