# Generated by Django 5.1.4 on 2026-10-08 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0035_iso_20816_por_base'),
        ('ensaios', '0011_base_oleo_novo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLimpezaRecomendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('codigo', models.CharField(help_text='X/Y/Z, ex.: 18/16/13', max_length=12, verbose_name='Código ISO 4406 recomendado')),
                ('fonte', models.CharField(blank=True, max_length=250, verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Meta de limpeza ISO 4406 recomendada',
                'verbose_name_plural': 'Metas de limpeza ISO 4406 recomendadas',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='produtofluido',
            name='densidade_g_cm3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Densidade do óleo novo (g/cm³)'),
        ),
        migrations.AddField(
            model_name='produtofluido',
            name='densidade_metodo',
            field=models.CharField(blank=True, help_text='Ex.: ASTM D4052, ASTM D1298.', max_length=30, verbose_name='Método da densidade'),
        ),
        migrations.AddField(
            model_name='produtofluido',
            name='densidade_temperatura_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ex.: 15 (ASTM D4052) ou 20 (ASTM D1298).', max_digits=4, null=True, verbose_name='Temperatura da densidade (°C)'),
        ),
        migrations.AddField(
            model_name='produtofluido',
            name='tbn_mgkoh_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Óleos de motor. Base do acompanhamento do TBN.', max_digits=6, null=True, verbose_name='TBN do óleo novo (mgKOH/g) — ASTM D2896'),
        ),
        migrations.AddField(
            model_name='referenciaparametro',
            name='tipo_equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencias_fluido', to='cadastros.tipoequipamento', verbose_name='Só para o tipo de equipamento'),
        ),
    ]
